---
apiVersion: v1
offerings:
  - name: deploy-arch-secrets-manager-custom-credentials-engine
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 6a7e04c0-f3ef-439b-9d3c-cdb4e583ae9c
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
        pre_validation: "tests/scripts/pre-validation-deploy-ce.sh"
        post_validation: "tests/scripts/post-validation-destroy-ce.sh"
