---
apiVersion: v1
offerings:
  - name: deploy-arch-secrets-manager-custom-credentials-engine
    kind: solution
    catalog_id: <TO BE ADDED>
    offering_id: <TO BE ADDED>
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: <TO BE ADDED>
          region: us-south
